### ISSUE TITLE
Add issue templates from scalabs/github-workflows

### ISSUE THREAD

**Issue by lukas-h** [dartclub/aquatic#6]
@LorenzMaehringer please do that

**Comment by LorenzMaehringer** [comment]
I dont have permission to push to dartclub/aquatic

![image](https://user-images.githubusercontent.com/108528644/212743400-89f50b6e-9bd5-41ae-a872-2486956d659e.png)

@lukas-h

**Comment by lukas-h** [comment]
should be resolved

**Comment by lukas-h** [comment]
@LorenzMaehringer please follow up here

**Comment by LorenzMaehringer** [comment]
my bad, the commit was still stuck in the upload queue.
